---
format: html
echo: false
warning: false
footer: "Made with [surveydown](https://surveydown.org)"
---

```{r}
library(surveydown)
library(tidyverse)
library(here)
library(glue)
library(kableExtra)
```

::: {#page00 .sd-page}

```{r}
cbc_options <- c(
  "Option 1" = "option_1",   
  "Option 2" = "option_2", 
  "Option 3" = "option_3"
)
```

```{r}

sd_output(id = 'images', type = 'question')

sd_question(
  type  = 'select',
  id    = 'budget',
  label = 'What is your budget range for your next vehicle?',
  option = c(
    "$4,999 or less" = "5000",
    "$5,000 - $7,500" = "7500",
    "$7,500 - $10,000" = "10000",
    "$10,000 - $12,500" = "12500",
    "$12,500 - $15,000" = "15000",
    "$15,000 - $17,500" = "17500",
    "$17,500 - $20,000" = "20000",
    "$20,000 - $22,500" = "22500",
    "$22,500 - $25,000" = "25000",
    "$25,000 - $27,500" = "27500",
    "$27,500 - $30,000" = "30000",
    "more than $30,000"= "35000"
  )
)

sd_next()
#sd_next(next_page  = "page3")


```

:::

::: {#page1 .sd-page}

```{r}

sd_output("make_table1") 

sd_question(
  type   = 'mc_buttons',
  id     = 'cbc_q1',
  label  = "If these were your only options, which would you choose?",
  option = cbc_options, 
  width = "600px"
)

sd_next()


```

:::

::: {#page2 .sd-page}

```{r}
sd_output("make_table2")

sd_question(
  type   = 'mc_buttons',
  id     = 'cbc_q2',
  label  = "If these were your only options, which would you choose?",
  option = cbc_options, 
  width = "600px"
)


sd_next()


```

:::


::: {#page3 .sd-page}

```{r}
sd_output("make_table3")

sd_question(
  type   = 'mc_buttons',
  id     = 'cbc_q3',
  label  = "If these were your only options, which would you choose?",
  option = cbc_options, 
  width = "600px"
)


sd_next()


```

:::


::: {#page4 .sd-page}

```{r}
sd_output("make_table4")

sd_question(
  type   = 'mc_buttons',
  id     = 'cbc_q4',
  label  = "If these were your only options, which would you choose?",
  option = cbc_options, 
  width = "600px"
)


sd_next()


```

:::


::: {#page5 .sd-page}

```{r}
sd_output("make_table5")

sd_question(
  type   = 'mc_buttons',
  id     = 'cbc_q5',
  label  = "If these were your only options, which would you choose?",
  option = cbc_options, 
  width = "600px"
)


sd_next()


```

:::


::: {#page6 .sd-page}

```{r}
sd_output("make_table6")

sd_question(
  type   = 'mc_buttons',
  id     = 'cbc_q6',
  label  = "If these were your only options, which would you choose?",
  option = cbc_options, 
  width = "600px"
)


sd_next()


```

:::


::: {#end .sd-page}

## End

This it the last page in the survey.

```{r}
sd_close("Exit Survey")
```

:::
