---
title: "get_quota"
format: html
editor: visual
---

```{r}
library(shiny)
library(surveydown)
library(DBI)
library(RPostgres)
library(dplyr)
library(tidyr)
```

# Get supabase data
```{r}
db <- sd_db_connect()
survey_data <- sd_get_data(db)

survey_data %>%
      mutate(current_page_summary=case_when(current_page=="screenout" ~ "Screenout",
                                            current_page=="end" ~ "Complete",
                                            TRUE ~ "In progress"
                                            ))%>% 
      group_by(current_page_summary) %>% 
      summarise(sample_size=n()) %>% 
      mutate(percentage=paste0(round(sample_size/sum(sample_size)*100,0),"%"))

survey_data %>%
     mutate(completion_status=case_when(current_page=="screenout" ~ "Screenout",
                                            current_page=="end" ~ "Complete",
                                            TRUE ~ "In progress"
                                            ))%>% 
      count(completion_status, name = "sample_size") %>%
      complete(completion_status, fill = list(sample_size = 0)) %>% 
      mutate(percentage=paste0(round(sample_size/sum(sample_size)*100,0),"%"))

survey_data %>%
      filter(current_page=="end") %>% 
      mutate(
        birth_year = as.numeric(birth_year),
        age = 2025 - birth_year # yob changed to age
      ) %>%
      mutate(age_group = case_when(
        age <= 24 ~ "18 - 24",
        age <= 34 ~ "25 - 34",
        age <= 44 ~ "35 - 44",
        age <= 54 ~ "45 - 54",
        age <= 64 ~ "55 - 64",
        age >= 65 ~ "65+"
      )) %>%
      mutate(age_group = factor(age_group, levels = c("18 - 24", "25 - 34", "35 - 44", "45 - 54", "55 - 64", "65+"))) %>%
      count(age_group, name = "sample_size") %>%
      complete(age_group, fill = list(sample_size = 0)) %>% 
      mutate(percentage_num=round(sample_size/sum(sample_size)*100,0),
             percentage=paste0(round(sample_size/sum(sample_size)*100,0),"%")
      ) %>% 
      mutate(population_target_num=c(18,17,17,18,14,16),
             population_target=paste0(population_target_num,"%")
      ) %>%
      mutate(discrepancy=paste0(percentage_num-population_target_num,"%")) %>% 
      select(-c(percentage_num,population_target_num)) 


survey_data %>%
      filter(current_page=="end") %>%
      mutate(gender=case_when(gender=="male" ~"male",
                              gender=="female" ~"female",
                              TRUE ~ sample(c("male", "female"), size = 1)
                              )) %>%
      mutate(gender = factor(gender, levels = c("male", "female"))) %>%
      count(gender, name = "sample_size") %>%
      complete(gender, fill = list(sample_size = 0)) %>% 
      mutate(percentage_num=round(sample_size/sum(sample_size)*100,0),
             percentage=paste0(round(sample_size/sum(sample_size)*100,0),"%")
      ) %>% 
      mutate(population_target_num=c(49,51),
             population_target=paste0(population_target_num,"%")
      ) %>%
      mutate(discrepancy=paste0(percentage_num-population_target_num,"%")) %>% 
      select(-c(percentage_num,population_target_num))  

survey_data %>%
      filter(current_page=="end") %>%
      mutate(hh_income=case_when(hh_income=="prefer_not_answer" ~ NA,
                                 TRUE ~ as.numeric(hh_income))) %>%
      filter(!is.na(hh_income)) %>% 
      mutate(hh_income= case_when(hh_income<=15000 ~ "< $15,000",
                                  hh_income<=25000 ~ "$15,000 - $24,999",
                                  hh_income<=45000 ~ "$25,000 - $49,999",
                                  hh_income<=75000 ~ "$50,000 - $74,999",
                                  hh_income<=95000 ~ "$75,000 - $99,999",
                                  hh_income<=145000 ~ "$100,000 - $149,999",
                                  TRUE ~ "$150,000+"
                                  )) %>%
      mutate(hh_income = factor(hh_income, levels = c("< $15,000",
                                                   "$15,000 - $24,999",
                                                   "$25,000 - $49,999",
                                                   "$50,000 - $74,999",
                                                   "$75,000 - $99,999",
                                                   "$100,000 - $149,999",
                                                   "$150,000+"))) %>%
      count(hh_income, name = "sample_size") %>%
      complete(hh_income, fill = list(sample_size = 0)) %>% 
      mutate(percentage_num=round(sample_size/sum(sample_size)*100,0),
             percentage=paste0(round(sample_size/sum(sample_size)*100,0),"%")
      ) %>% 
      mutate(population_target_num=c(12,10,23,18,12,13,11),
             population_target=paste0(population_target_num,"%")
      ) %>%
      mutate(discrepancy=paste0(percentage_num-population_target_num,"%")) %>% 
      select(-c(percentage_num,population_target_num))
      
```

## Define UI
```{r}
# Define UI
ui <- fluidPage(
  titlePanel("Survey Dashboard"),
  sidebarLayout(
    sidebarPanel(
      helpText("Summary of survey responses")
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Age Distribution", plotOutput("agePlot")),
        tabPanel("Gender Distribution", plotOutput("genderPlot")),
        tabPanel("Income Distribution", plotOutput("incomePlot"))
      )
    )
  )
)
```

