# ! JUST READ - don't change the content of this file
# Server settings with final resolved parameters
# (includes sd_server() parameters, YAML header, and defaults)
use_cookies: no
auto_scroll: no
rate_survey: no
all_questions_required: no
system_language: en
highlight_unanswered: yes
highlight_color: gray
capture_metadata: yes

