---
title: "4_modeling"
output: html_notebook
---
# Library
```{r}
library(tidyverse)
library(stringr)
library(apollo)
`%notin%`<-Negate(`%in%`)
```

# Read Data
```{r}
# Import raw data
data_covariates <- read_csv(here(
  "code files",
  "pilot",
  "Battery_analysis",
  "data_covariates.csv"
))


choice_data <- read_csv(here(
  "code files",
  "pilot",
  "data",
  # "vehicle_choice_data.csv",
  "battery_choice_data.csv"
))

data<-data_raw %>% 
  filter(session_id %in% choice_data$session_id) %>% 
  select(-starts_with("time_"))
```

#----------------------------------
# Data Preparation
#----------------------------------
# Socio-demographics
```{r}
# colnames(data)

data<-data %>% 
  mutate(age_num=2025-birth_year,
         gender_cate=case_when(gender=="prefer_not_answer"~"prefer_not_answer",
                               gender %notin% c("male", "female") ~"other", 
                               T~gender),
         ethnicity_cate=case_when(ethnicity=="no"~"non-hispanic", T~"hispanic"),
         race_cate=case_when(race=="white"~"white_only",
                        race=="african_american" ~"african_american_only", 
                               T~"other"),
         education_cate=case_when(education=="prefer_not_answer"~"prefer_not_answer",
                                  education %in% c("below_high_school","high_school") ~"high_school",
                                  education %in% c("college_less","college_more","technical") ~"some_college",
                                  education %in% c("bachelor","Postgraduate courses")~"bachelor",
                                  T~"graduate"
                                  ),
         student_cate=case_when(str_detect(employment,"student") ~"student",
                                employment=="prefer_not_answer" ~ "prefer_not_answer",
                                T~"non-student"),
         employment_cate=case_when(employment=="prefer_not_answer" ~ "prefer_not_answer",
           str_detect(employment,"full_time") ~"full_time", 
                                   str_detect(employment,"part_time") ~"part_time", 
                                   T~"not_employed"),
         hhincome_num=as.numeric(hh_income),
         hhsize_num=case_when(hh_size=="more_than_5" ~6, T~as.numeric(hh_size)),
         hhtenure_cate=case_when(housing_tenure %in% c("own","rent") ~ housing_tenure, 
                                 housing_tenure=="do_not_know" ~"prefer_not_answer", 
                                 T~"other"),
         hhtype_cate=case_when(housing_type %in% c("sf_detached","sf_attached") ~ housing_type,
                               str_detect(housing_type,"apart") ~"apart",
                               T~"other")
         ) %>% 
  mutate(final_weights=1)

```

# Attitudes
## BEV
Explortory Factor analysis
(http://www.di.fc.ul.pt/~jpn/r/factoranalysis/factoranalysis.html)
```{r}
# colnames(data)
library(psych)
library(nFactors)
library(GPArotation)
         
att<-data %>%
  # filter(attitudes_2_a_attention_check_agree=="strongly_agree")%>% 
  select(!attitudes_2_a_attention_check_agree) %>% 
  select(session_id,attitudes_1_a_ev_norm:attitudes_2_a_ev_battery_function, -(contains("battery"))) %>%
  mutate(across(starts_with("attitudes_"),
                ~ case_match(.,
                  "strongly_disagree" ~ 1,
                  "somewhat_disagree" ~ 2,
                  "neutral"           ~ 3,
                  "somewhat_agree"    ~ 4,
                  "strongly_agree"    ~ 5,
                  .default = NA_integer_)))

  
# summary(att)
att <- as.data.frame(att[complete.cases(att),])


##Bartlett’s test is highly significant,  p-val < .05, and therefore factor analysis is appropriate. Then, we could get the determinant
bartl_test = cortest.bartlett(att[,c(2:ncol(att))])
bartl_test

## The determinant value is greater than the necessary value of 0.00001. As such, the determinant does not seem problematic. 
ncol<-as.numeric(ncol(att[,c(2:ncol(att))]))
corr <- round(cor(att[,c(2:ncol)]), 1)
det(corr)


# Determine Number of Factors to Extract
ev <- eigen(cor(att[,c(2:ncol(att))])) # get eigenvalues
ap <- parallel(subject=nrow(att[,c(2:ncol(att))]),var=ncol(att[,c(2:ncol(att))]),
  rep=100,cent=.05)
nS <- nScree(x=ev$values, aparallel=ap$eigen$qevpea)
plotnScree(nS)

######### Factor Analysis #########
# fit <- factanal(att[,c(2:ncol(att))], 3, rotation="none", score = "Bartlett")
# fit <- factanal(att[,c(2:ncol(att))], 4, rotation="none", score = "Bartlett")
fit <- factanal(att[,c(2:ncol(att))], 2, rotation="promax", score = "Bartlett")

# fit <- factanal(att[,c(2:ncol(att))], 3, rotation="none", score = "Bartlett")

# fit_oblimin<-GPFoblq(fit$loadings, normalize=FALSE, method = "oblimin")

# fit_oblimin <- fa(
#   att[,c(2:ncol(att))],
#   nfactors = 3,
#   fm = "ml",
#   SMC = TRUE, #
#   rotate = "oblimin",
#   scores = "tenBerge", # "Bartlett", #
#   oblique.scores = "TRUE" # scores computed based on pattern matrix
#   )

# fit_oblimin$loadings

print(fit, digits=2, cutoff=0.3, sort=TRUE)
# print(fit_oblimin, digits=2, cutoff=0.3, sort=TRUE)

# print(fit_oblimin_2$loadings, digits=2, cutoff=0.3, sort=TRUE)
l<-fit$loadings
# l<-fit_oblimin$loadings
l.table<-data.frame(matrix(as.numeric(l), attributes(l)$dim, dimnames=attributes(l)$dimnames))
l.table<-cbind(row.names(l.table),l.table)
# library(xlsx)
# write.xlsx(l.table,paste0("/Users/wuxiatian/Library/CloudStorage/Box-Box/Covid_Survey/SCAG/Factor_Analysis/A_fact_5_promax_loadings.xlsx"))


######### Factor Loading
scores<-data.frame(fit$scores)
att_a_FC<-cbind(att,scores) %>% 
  select(session_id,Factor1, Factor2)

colnames(att_a_FC)<-c("session_id","FA_EV_benefit","FA_EV_anxiety")
  
data$FA_EV_benefit<-NULL
data$FA_EV_anxiety<-NULL

data <-data %>% 
  merge(att_a_FC,by="session_id",all.x=T)

```
##Other
```{r}
data<-data %>%
  mutate(ATT_EVB_environment=attitudes_2_a_ev_battery_environment,
         ATT_EVB_function=attitudes_2_a_ev_battery_function,
         ATT_techsavvy=attitudes_2_b_tech_savvy,
         ATT_risktaker=attitudes_2_b_risk_taker,
         ATT_climate=climate_change,
         ATT_political=political_view,
         ATT_voting=party_voting)
```


# Knowledge
```{r}
colnames(data)
table(data$know_electric_vehicle)
table(data$write_electric_name)
str(data$birth_year)

data<-data %>% 
  mutate(knowledge_gas=case_when(run_on_gasoline=="hev, phev" ~2,
                                 str_detect(run_on_gasoline,"hev") | str_detect(run_on_gasoline,"phev")~1,
                                 T ~ 0
                                 ),
         knowledge_plugin=case_when(plugged_in=="phev, bev" ~2,
                                 str_detect(plugged_in,"bev") | str_detect(run_on_gasoline,"phev")~1,
                                 T ~ 0
                                 ),
         knowledge_ev=case_when(know_electric_vehicle=="yes" ~1, T~0), # need more data cleaning
         knowledge_subsidy=case_when(max_subsidy=="7500"~1, T~0)
         )
```

# vehicle attribute
```{r}
colnames(data)
table(data$household_veh_fuel)
table(data$household_veh_count)
str(data$birth_year)

data<-data %>% 
  mutate(Veh_hh_count=household_veh_count,
         Veh_hh_fuel=case_when(household_veh_fuel=="other" ~"other",
                               household_veh_fuel=="icev" ~"icev_only",
                               str_detect(household_veh_fuel,"icev") ~"ev_mix",
                               T~"ev_only"
                               ),
         EV_charger=charger_access,
         EV_neighbor=neighbor_ev_info,
         
         Veh_primary_fuel=case_when(is.na(primary_veh_fuel)~household_veh_fuel,
                                    T ~ primary_veh_fuel)
         
         )

table(data$Veh_primary_fuel)
```

# -------------------------------
# Summary Statistics
# -------------------------------
## Dataset
```{r}
# table(data$next_veh_fuel_new_bev)
# table(data$next_veh_fuel_used_bev)

summary_dt<-data %>% 
  select(ends_with("_num"),
         ends_with("_cate"),
         starts_with("FA_"),
         starts_with("ATT_"),
         starts_with("knowledge_"),
         starts_with("Veh_"),
         starts_with("EV_"),
         
         next_veh_fuel_new_bev,
         next_veh_fuel_used_bev,
         
         final_weights
         )

```

## Recode
```{r}
summary_dt <- summary_dt %>%
  mutate(across(
    c(ends_with("_cate"),
      starts_with("ATT_"),
      starts_with("knowledge_"),
      Veh_hh_fuel,
      starts_with("EV_"),    
      next_veh_fuel_used_bev,
      next_veh_fuel_new_bev),
    factor
  ))

varfactor_names <- names(select(data, ends_with("_cate"),
      starts_with("ATT_"),
      starts_with("knowledge_"),
      Veh_hh_fuel,
      starts_with("EV_"),
      next_veh_fuel_used_bev,
      next_veh_fuel_new_bev
      )
      )

lapply(summary_dt[varfactor_names], levels)

summary_dt <- summary_dt %>%
  mutate(
    next_veh_fuel_used_bev=factor(next_veh_fuel_used_bev,
                       levels = c("very_unlikely","somewhat_unlikely","neutral","somewhat_likely","very_likely"),
                       ordered = TRUE),
    next_veh_fuel_new_bev=factor(next_veh_fuel_new_bev,
                       levels = c("very_unlikely","somewhat_unlikely","neutral","somewhat_likely","very_likely"),
                       ordered = TRUE),
    gender_cate = factor(gender_cate,
                       levels = c("female","male","other"),
                       labels = c("female","male","gender_other"),
                       ordered = TRUE),
    ethnicity_cate = factor(ethnicity_cate,
                          labels = c("hispanic","non-hispanic"),
                          ordered = TRUE),
    race_cate = factor(race_cate,
                       levels = c("white_only","african_american_only","other"),
                       labels = c("White only","African American only","race_other"),
                       ordered = TRUE),
    education_cate= factor(education_cate,
                       levels = c("high_school","some_college","bachelor","graduate"),
                       labels = c("high school or under","some college","bachelor","master or above"),
                       ordered = TRUE),
   student_cate = factor(student_cate,
                       levels = c("student","non-student","prefer_not_answer"),
                       labels = c("student","non-student","stu_prefer not to answer"),
                       ordered = TRUE),
   employment_cate = factor(employment_cate,
                       levels = c("full_time","part_time","not_employed","prefer_not_answer" ),
                       labels = c("full-time","part-time","not employed","employ_prefer not to answer" ),
                       ordered = TRUE),
   hhtenure_cate = factor(hhtenure_cate,
                       levels = c("own","rent","other"),
                       labels = c("own","rent","hhtenure_other"),
                       ordered = TRUE),
   hhtype_cate = factor(hhtype_cate,
                       levels = c("sf_detached","sf_attached","apart","other"),
                       labels = c("detached single family house","attached single family house","apartment","hhtype_other"),
                       ordered = TRUE),
   ATT_EVB_environment = factor(ATT_EVB_environment,
                       levels = c("strongly_disagree","somewhat_disagree","neutral","somewhat_agree","strongly_agree"),
                       labels = c("EVBe_strongly disagree","EVBe_somewhat disagree","EVBe_neither agree nor disagree","EVBe_somewhat agree","EVBe_strongly agree"),
                       ordered = TRUE),
   ATT_EVB_function = factor(ATT_EVB_function,
                       levels = c("strongly_disagree","somewhat_disagree","neutral","somewhat_agree","strongly_agree"),
                       labels = c("EVBf_strongly disagree","EVBf_somewhat disagree","EVBf_neither agree nor disagree","EVBf_somewhat agree","EVBf_strongly agree"),
                       ordered = TRUE),
   ATT_techsavvy = factor(ATT_techsavvy,
                       levels = c("strongly_disagree","somewhat_disagree","neutral","somewhat_agree","strongly_agree"),
                       labels = c("ATTt_strongly disagree","ATTt_somewhat disagree","ATTt_neither agree nor disagree","ATTt_somewhat agree","ATTt_strongly agree"),
                       ordered = TRUE),
   ATT_risktaker = factor(ATT_risktaker,
                       levels = c("strongly_disagree","somewhat_disagree","neutral","somewhat_agree","strongly_agree"),
                       labels = c("ATTr_strongly disagree","ATTr_somewhat disagree","ATTr_neither agree nor disagree","ATTr_somewhat agree","ATTr_strongly agree"),
                       ordered = TRUE),
   ATT_climate = factor(ATT_climate,
                       levels = c("not_at_all","a_little","moderate","a_lot","great_deal"),
                       labels = c("not at all","a little","a moderate amount"  
,"a lot","a great_deal"),
                       ordered = TRUE),
  ATT_political = factor(ATT_political,
                       levels = c("very_conservative","conservative","moderate","liberal","very_liberal","other","prefer_not_answer"),
                       labels = c("very conservative","conservative","moderate","liberal","very liberal","other","political_prefer not to answer"),
                       ordered = TRUE),
   ATT_voting = factor(ATT_voting,
                       levels = c("democratic","republican","independent","prefer_not_answer"),
                       labels = c("Democratic","Republican","I am independent","voting_prefer not to answer"),
                       ordered = TRUE),
knowledge_gas = factor(knowledge_gas,
                       levels = c("0","1","2"),
                       labels = c("gas_no knowledge","gas_partial knowledge","gas_full knowledge"),
                       ordered = TRUE),
knowledge_plugin = factor(knowledge_plugin,
                       levels = c("0","1","2"),
                       labels = c("plugin_no knowledge","plugin_partial knowledge","plugin_full knowledge"),
                       ordered = TRUE),
knowledge_ev = factor(knowledge_ev,
                       levels = c("0","1"),
                       labels = c("ev_no knowledge","ev_full knowledge"),
                       ordered = TRUE),
knowledge_subsidy = factor(knowledge_subsidy,
                       levels = c("0","1"),
                       labels = c("subsidy_no knowledge","subsidy_full knowledge"),
                       ordered = TRUE),

Veh_hh_fuel = factor(Veh_hh_fuel,
                       levels = c("icev_only","ev_only","ev_mix","other"),
                       labels = c("ICEV-only","EV-only","EV-mixed-fuel","Vehfuel_other"),
                       ordered = TRUE),
EV_charger = factor(EV_charger,
                       levels = c("no","yes","not_sure"),
                       labels = c("EVc_no","EVc_yes","EVc_not sure"),
                       ordered = TRUE),
EV_neighbor = factor(EV_neighbor,
                       levels = c("no","yes","not_sure"),
                       labels = c("EVn_no","EVn_yes","EVn_not sure"),
                       ordered = TRUE)
  )
```


## New BEV
### Total - column wise
```{r}
library(rlang)

varfactor <- data %>%
  select(ends_with("_cate"), 
         starts_with("ATT_"),
         starts_with("knowledge_"),
         Veh_hh_fuel,
         starts_with("EV_")
         ) %>%
  names() %>%
  syms()

cross_tabs_cat<-data.frame()
for (var in seq_along(varfactor)){
  new_cross_tab<-summary_dt %>%
  group_by(next_veh_fuel_new_bev,!! varfactor[[var]]) %>% # Unquote with !!
    # summarise(n=sum(final_weights)) %>%
    summarise(n=sum(final_weights)) %>%
    filter(!is.na(!! varfactor[[var]])) %>%
  mutate(perc=round(n/sum(n),3)) %>%
  setNames(.,c("next_veh_fuel_new_bev","Variables","n","perc"))
  cross_tabs_cat<-rbind(as.data.frame(cross_tabs_cat),as.data.frame(new_cross_tab))
}

cross_tabs_cat_wide_perc<-cross_tabs_cat %>%
  select(-n) %>%
  # mutate(rowid=c(1:nrow(cross_tabs_cat))) %>% 
  pivot_wider(names_from = next_veh_fuel_new_bev,values_from=perc)

cross_tabs_cat_wide_n<-cross_tabs_cat %>%
  select(-perc) %>%
  # mutate(rowid=c(1:nrow(cross_tabs_cat))) %>% 
  pivot_wider(names_from = next_veh_fuel_new_bev,values_from=n)


cross_tabs_cat_pop<-data.frame()
for (var in seq_along(varfactor)){
  new_cross_tab<-summary_dt %>%
  group_by(!! varfactor[[var]]) %>% # Unquote with !!
  summarise(n=sum(final_weights)) %>%
    filter(!is.na(!! varfactor[[var]])) %>%
  mutate(perc=round(n/sum(n),3)) %>%
  setNames(.,c("Variables","n","perc"))
  cross_tabs_cat_pop<-rbind(as.data.frame(cross_tabs_cat_pop),as.data.frame(new_cross_tab))
}


cross_tabs_cat_pop_wide_n<-cross_tabs_cat_pop %>%
  select(!perc) 

cross_tabs_cat_pop_wide_perc<-cross_tabs_cat_pop %>%
  select(!n) 

## Continuous vehicle

varcon <- data %>%
  select(ends_with("_num"), 
         starts_with("FA_"),
         Veh_hh_count) %>%
  names() %>%
  syms()

varcon_names <- names(select(data, ends_with("_num"), starts_with("FA_"), starts_with("knowledge_"), Veh_hh_count))
varcon_names_list<-paste0('"', varcon_names, '"', collapse = ", ")


cross_tabs_con <- data.frame()

for (var in seq_along(varcon)){
  new_cross_tab<-summary_dt %>%
     filter(!is.na(!! varcon[[var]])) %>% 
    group_by(next_veh_fuel_new_bev) %>% # Unquote with !!
    summarise(n=sum(!! varcon[[var]]*final_weights),pop=sum(final_weights)) %>%
    ungroup() %>%
    mutate(perc=round(n/pop,3))

  cross_tabs_con<-rbind(as.data.frame(cross_tabs_con),as.data.frame(new_cross_tab))
}

cross_tabs_con_wide<-cross_tabs_con %>%
  mutate(Variables=c(rep(c("age_num", "hhincome_num", "hhsize_num", "FA_EV_benefit", "FA_EV_anxiety", "Veh_hh_count"
  ),each=5))) %>%
   select(next_veh_fuel_new_bev, Variables,perc) %>%
   pivot_wider(names_from = next_veh_fuel_new_bev,values_from=perc)

cross_tabs_con_pop <- data.frame()
for (var in seq_along(varcon)){
  new_cross_tab<-summary_dt %>%
     filter(!is.na(!! varcon[[var]])) %>% 
    summarise(n=sum(!! varcon[[var]]*final_weights),pop=sum(final_weights)) %>%
    ungroup() %>%
    mutate(perc=round(n/pop,3))
  cross_tabs_con_pop<-rbind(as.data.frame(cross_tabs_con_pop),as.data.frame(new_cross_tab))
}

cross_tabs_con_pop_wide<-cross_tabs_con_pop %>%
  mutate(Variables=c("age_num", "hhincome_num", "hhsize_num", "FA_EV_benefit", "FA_EV_anxiety", "Veh_hh_count"
)) %>% 
  select(Variables, perc) %>% 
  setNames(c("Variables", "n"))

cross_tabs<-rbind(cross_tabs_cat_wide_perc,cross_tabs_con_wide)

cross_tabs_pop<-rbind(cross_tabs_cat_pop_wide_n,cross_tabs_con_pop_wide)
# cross_tabs[is.na(cross_tabs)]<-0

cross_tabs_new_bev<-cross_tabs_pop %>%
  inner_join(cross_tabs,by="Variables")

cate_vars <- summary_dt %>% 
  select_if(~ is.factor(.) || is.character(.)) %>% 
  select(!starts_with("next_veh"))
vars <- lapply(cate_vars, function(x) levels(as.factor(x)))

df_levels <- tibble(variable = names(vars), levels_list = vars) %>%
  unnest(cols = c(levels_list)) %>%
  rename(level = levels_list)

cross_tabs_new_bev<-df_levels %>% 
  full_join(cross_tabs_new_bev, by=c("level"="Variables"))

```

## Used BEV
### Total - column wise
```{r}
library(rlang)

varfactor <- data %>%
  select(ends_with("_cate"), 
         starts_with("ATT_"),
         starts_with("knowledge_"),
         Veh_hh_fuel,
         starts_with("EV_")
         ) %>%
  names() %>%
  syms()

cross_tabs_cat<-data.frame()
for (var in seq_along(varfactor)){
  new_cross_tab<-summary_dt %>%
  group_by(next_veh_fuel_used_bev,!! varfactor[[var]]) %>% # Unquote with !!
    # summarise(n=sum(final_weights)) %>%
    summarise(n=sum(final_weights)) %>%
    filter(!is.na(!! varfactor[[var]])) %>%
  mutate(perc=round(n/sum(n),3)) %>%
  setNames(.,c("next_veh_fuel_used_bev","Variables","n","perc"))
  cross_tabs_cat<-rbind(as.data.frame(cross_tabs_cat),as.data.frame(new_cross_tab))
}

cross_tabs_cat_wide_perc<-cross_tabs_cat %>%
  select(-n) %>%
  # mutate(rowid=c(1:nrow(cross_tabs_cat))) %>% 
  pivot_wider(names_from = next_veh_fuel_used_bev,values_from=perc)

cross_tabs_cat_wide_n<-cross_tabs_cat %>%
  select(-perc) %>%
  # mutate(rowid=c(1:nrow(cross_tabs_cat))) %>% 
  pivot_wider(names_from = next_veh_fuel_used_bev,values_from=n)


cross_tabs_cat_pop<-data.frame()
for (var in seq_along(varfactor)){
  new_cross_tab<-summary_dt %>%
  group_by(!! varfactor[[var]]) %>% # Unquote with !!
  summarise(n=sum(final_weights)) %>%
    filter(!is.na(!! varfactor[[var]])) %>%
  mutate(perc=round(n/sum(n),3)) %>%
  setNames(.,c("Variables","n","perc"))
  cross_tabs_cat_pop<-rbind(as.data.frame(cross_tabs_cat_pop),as.data.frame(new_cross_tab))
}


cross_tabs_cat_pop_wide_n<-cross_tabs_cat_pop %>%
  select(!perc) 

cross_tabs_cat_pop_wide_perc<-cross_tabs_cat_pop %>%
  select(!n) 

## Continuous vehicle

varcon <- data %>%
  select(ends_with("_num"), 
         starts_with("FA_"),
         Veh_hh_count) %>%
  names() %>%
  syms()

varcon_names <- names(select(data, ends_with("_num"), starts_with("FA_"), starts_with("knowledge_"), Veh_hh_count))
varcon_names_list<-paste0('"', varcon_names, '"', collapse = ", ")


cross_tabs_con <- data.frame()

for (var in seq_along(varcon)){
  new_cross_tab<-summary_dt %>%
     filter(!is.na(!! varcon[[var]])) %>% 
    group_by(next_veh_fuel_used_bev) %>% # Unquote with !!
    summarise(n=sum(!! varcon[[var]]*final_weights),pop=sum(final_weights)) %>%
    ungroup() %>%
    mutate(perc=round(n/pop,3))

  cross_tabs_con<-rbind(as.data.frame(cross_tabs_con),as.data.frame(new_cross_tab))
}

cross_tabs_con_wide<-cross_tabs_con %>%
  mutate(Variables=c(rep(c("age_num", "hhincome_num", "hhsize_num", "FA_EV_benefit", "FA_EV_anxiety", "Veh_hh_count"
  ),each=5))) %>%
   select(next_veh_fuel_used_bev, Variables,perc) %>%
   pivot_wider(names_from = next_veh_fuel_used_bev,values_from=perc)

cross_tabs_con_pop <- data.frame()
for (var in seq_along(varcon)){
  new_cross_tab<-summary_dt %>%
     filter(!is.na(!! varcon[[var]])) %>% 
    summarise(n=sum(!! varcon[[var]]*final_weights),pop=sum(final_weights)) %>%
    ungroup() %>%
    mutate(perc=round(n/pop,3))
  cross_tabs_con_pop<-rbind(as.data.frame(cross_tabs_con_pop),as.data.frame(new_cross_tab))
}

cross_tabs_con_pop_wide<-cross_tabs_con_pop %>%
  mutate(Variables=c("age_num", "hhincome_num", "hhsize_num", "FA_EV_benefit", "FA_EV_anxiety", "Veh_hh_count"
)) %>% 
  select(Variables, perc) %>% 
  setNames(c("Variables", "n"))

cross_tabs<-rbind(cross_tabs_cat_wide_perc,cross_tabs_con_wide)

cross_tabs_pop<-rbind(cross_tabs_cat_pop_wide_n,cross_tabs_con_pop_wide)
# cross_tabs[is.na(cross_tabs)]<-0

cross_tabs_used_bev<-cross_tabs_pop %>%
  inner_join(cross_tabs,by="Variables")

cate_vars <- summary_dt %>% 
  select_if(~ is.factor(.) || is.character(.)) %>% 
  select(!starts_with("next_veh"))
vars <- lapply(cate_vars, function(x) levels(as.factor(x)))

df_levels <- tibble(variable = names(vars), levels_list = vars) %>%
  unnest(cols = c(levels_list)) %>%
  rename(level = levels_list)

cross_tabs_used_bev<-df_levels %>% 
  full_join(cross_tabs_used_bev, by=c("level"="Variables"))

```

