---
title: "4_modeling"
output: html_notebook
---
# Library
```{r}
library(tidyverse)
library(stringr)
library(apollo)
library(here)
`%notin%`<-Negate(`%in%`)
```

# Read Data
```{r}
# Import raw data
data_covariates <- read_csv(here(
  "code files",
  "pilot",
  "Battery_analysis",
  "data_covariates.csv"
))


choice_data <- read_csv(here(
  "code files",
  "pilot",
  "data",
  # "vehicle_choice_data.csv",
  "battery_choice_data.csv"
))

data_covariates<-data_covariates %>% 
  filter(session_id %in% choice_data$session_id) %>% 
  select(-starts_with("time_"))

data_DCE<-choice_data %>%
  # left_join(data_covariates %>% select(session_id,ends_with("_num",)))
  mutate(
    veh_mileage = veh_mileage / 10000, #3 - 6
    veh_price = veh_price / 10000, # 0.5 - 6
    battery_range_year0 = battery_range_year0 / 100, # 1-3
    battery_range_year3 = battery_range_year3 / 100, # 1-3
    battery_range_year8 = battery_range_year8 / 100, # 0.5 - 2
    battery_degradation = (battery_degradation * 10)
  ) %>%
  select(
    -starts_with("battery_health"),
    -starts_with("time"),
    -session_id,
    -vehicle_type,
    -battery_condition)

```

# Model
## Simple MNL 
### DCE only
```{r}
# Initialize
apollo_initialise()

# Define core controls
apollo_control = list(
  modelName = "MNL_DCE",
  modelDescr = "MNL_DCE",
  indivID = "respID",
  mixing = FALSE
)

database <- data_DCE
# example: get vector of distinct alternative names present in data
alts <- sort(unique(database$profileID))   # e.g., c("A","B","C","D")

# if your df_long already has a column 'avail' (0/1) per row,
# and each row corresponds to one alt, we can create avail list from that:
avail_list <- lapply(alts, function(a) {
  as.numeric(database$profileID == a )
})
names(avail_list) <- alts

apollo_beta <- c(
  b_mileage = 0,
  b_price = 0,
  b_range_y0 = 0,
  b_degradation=0,
  b_refurbishpack=0,
  b_refurbishcell=0,
  b_nochoice=0
)

apollo_probabilities <- function(apollo_beta, apollo_inputs, functionality = "estimate") {

  apollo_attach(apollo_beta, apollo_inputs)
  on.exit(apollo_detach(apollo_beta, apollo_inputs))

  ### Create list of probabilities P
  P = list()
  
  ### List of utilities
  V <- list()
  
  # V needs an entry per alt name; use the long-data attributes
  for (a in alts) {
    # each row of df_long will have price/range/charge_time for that alt
    V[[a]] <-  b_mileage * veh_mileage+
   b_price * veh_price+
   b_range_y0 * battery_range_year0+
   b_degradation * battery_degradation+
   b_refurbishpack * (battery_refurbish=="packreplace")+
   b_refurbishcell * (battery_refurbish=="cellreplace")+
   b_nochoice * (choice==0)
  }
  
  # MNL model
  P <- apollo_mnl(
    V = V,
    choiceVar = choice,
    avail = list(A = 1, B = 1)
  )

  P <- apollo_panelProd(P, apollo_inputs)
  P <- apollo_prepareProb(P, apollo_inputs, functionality)
  return(P)
}

```

